from django.conf.urls.defaults import patterns
from django.conf.urls.defaults import url
import views

urlpatterns = patterns('',
    url(r'^$',
        views.wettkaempfe_get, name="wettkaempfe_get"),
    (r'^add/$',
        views.wettkaempfe_add, {}, "wettkaempfe_add"),
    (r'^(?P<jahr>\d+)/$',
        views.wettkaempfe_by_year, {}, "wettkaempfe_by_year"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/$',
        views.wettkampf_get, {}, "wettkampf_get"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/update/$',
        views.wettkampf_update, {}, "wettkampf_update"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/delete/$',
        views.wettkampf_delete_confirm, {}, "wettkampf_delete_confirm"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/add/$',
        views.disziplinen_add, {}, "disziplinen_add"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/$',
        views.disziplin_get, {}, "disziplin_get"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/update/$',
        views.disziplin_update, {}, "disziplin_update"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/delete/$',
        views.disziplin_delete_confirm, {}, "disziplin_delete_confirm"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/posten/$',
        views.posten_list, {}, "posten_list"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/posten/(?P<posten>[-\w]+)$',
        views.posten_get, {}, "posten_get"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/posten/(?P<posten>[-\w]+)/update/$',
        views.posten_update, {}, "posten_update"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/posten/(?P<posten>[-\w]+)/delete/$',
        views.posten_delete_confirm, {}, "posten_delete_confirm"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/startliste/$',
        views.startliste, {}, "startliste"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/startliste/pdf/$',
        views.startliste_einzelfahren_pdf, {}, "startliste_einzelfahren_pdf"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/teilnehmer/(?P<startnummer>\d+)/$',
        views.teilnehmer_get, {}, "teilnehmer_get"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/teilnehmer/(?P<startnummer>\d+)/update/$',
        views.teilnehmer_update, {}, "teilnehmer_update"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/teilnehmer/(?P<startnummer>\d+)/delete/$',
        views.teilnehmer_delete_confirm, {}, "teilnehmer_delete_confirm"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/bewertungen/$',
        views.bewertungen, {}, "bewertungen"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/postenblatt/(?P<posten>[-\w]+)/$',
        views.postenblatt, {}, "postenblatt"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/postenblatt/(?P<posten>[-\w]+)/update/$',
        views.postenblatt_update, {}, "postenblatt_update"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/richtzeiten/$',
        views.richtzeiten, {}, "richtzeiten"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/richtzeiten/pdf/$',
        views.richtzeiten_pdf, {}, "richtzeiten_pdf"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/richtzeit/(?P<posten>[-\w]+)/$',
        views.richtzeit, {}, "richtzeit"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/richtzeit/(?P<posten>[-\w]+)/update/$',
        views.richtzeit_update, {}, "richtzeit_update"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/notenliste/$',
        views.notenliste, {}, "notenliste"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/notenblaetter/$',
        views.notenblaetter_pdf, {}, "notenblaetter_pdf"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/rangliste/$',
        views.rangliste, {}, "rangliste"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/rangliste/pdf/$',
        views.rangliste_pdf_all, {}, "rangliste_pdf_all"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/rangliste/(?P<kategorie>[-\w]+)/$',
        views.rangliste, {}, "rangliste"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/rangliste/(?P<kategorie>[-\w]+)/pdf/$',
        views.rangliste_pdf, {}, "rangliste_pdf"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/kranzlimiten/$',
        views.kranzlimiten, {}, "kranzlimiten"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/kranzlimiten/update$',
        views.kranzlimiten_update, {}, "kranzlimiten_update"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/notenblatt/$',
        views.notenblatt, {}, "notenblatt"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/notenblatt/(?P<startnummer>\d+)/$',
        views.notenblatt, {}, "notenblatt"),
    (r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/notenblatt/(?P<startnummer>\d+)/pdf/$',
        views.notenblatt_pdf, {}, "notenblatt_pdf"),
)
