from django.urls import include, path, re_path
from . import views

bootfaehrenbau_patterns = [
    re_path(r'^$',
        views.bootfaehrenbau_get, {}, "bootfaehrenbau_get"),
    re_path(r'^eingabe/$',
        views.bootfaehrenbau_eingabe, {}, "bootfaehrenbau_eingabe"),
    re_path(r'^update/(?P<startnummer>\d+)$',
        views.bootfaehrenbau_update, {}, "bootfaehrenbau_update"),
    re_path(r'^delete/(?P<startnummer>\d+)$',
        views.bootfaehrenbau_delete, {}, "bootfaehrenbau_delete"),
    re_path(r'^rangliste/$',
        views.bootfaehrenbau_rangliste, {}, "bootfaehrenbau_rangliste"),
    re_path(r'^rangliste/(?P<kategorie>[-\w]+)/$',
        views.bootfaehrenbau_rangliste, {}, "bootfaehrenbau_rangliste"),
    re_path(r'^rangliste/(?P<kategorie>[-\w]+)/pdf/$',
        views.bootfaehrenbau_rangliste_pdf, {}, "bootfaehrenbau_rangliste_pdf"),
    re_path(r'^kranzlimite/(?P<kategorie>[-\w]+)/update$',
        views.bootfaehrenbau_kranzlimite_update, {}, "bootfaehrenbau_kranzlimite_update"),
]

gruppenschnueren_patterns = [
    re_path(r'^$',
        views.gruppenschnueren_get, {}, "gruppenschnueren_get"),
    re_path(r'^eingabe/$',
        views.gruppenschnueren_eingabe, {}, "gruppenschnueren_eingabe"),
    re_path(r'^update/(?P<startnummer>\d+)$',
        views.gruppenschnueren_update, {}, "gruppenschnueren_update"),
    re_path(r'^delete/(?P<startnummer>\d+)$',
        views.gruppenschnueren_delete, {}, "gruppenschnueren_delete"),
    re_path(r'^rangliste/$',
        views.gruppenschnueren_rangliste, {}, "gruppenschnueren_rangliste"),
    re_path(r'^rangliste/(?P<kategorie>[-\w]+)/$',
        views.gruppenschnueren_rangliste, {}, "gruppenschnueren_rangliste"),
    re_path(r'^rangliste/(?P<kategorie>[-\w]+)/pdf/$',
        views.gruppenschnueren_rangliste_pdf, {}, "gruppenschnueren_rangliste_pdf"),
    re_path(r'^kranzlimite/(?P<kategorie>[-\w]+)/update$',
        views.gruppenschnueren_kranzlimite_update, {}, "gruppenschnueren_kranzlimite_update"),
]

einzelschnueren_patterns = [
    re_path(r'^$',
        views.einzelschnueren_get, {}, "einzelschnueren_get"),
    re_path(r'^eingabe/$',
        views.einzelschnueren_eingabe, {}, "einzelschnueren_eingabe"),
    re_path(r'^update/(?P<startnummer>\d+)$',
        views.einzelschnueren_update, {}, "einzelschnueren_update"),
    re_path(r'^delete/(?P<startnummer>\d+)$',
        views.einzelschnueren_delete, {}, "einzelschnueren_delete"),
    re_path(r'^rangliste/$',
        views.einzelschnueren_rangliste, {}, "einzelschnueren_rangliste"),
    re_path(r'^rangliste/(?P<kategorie>[-\w]+)/$',
        views.einzelschnueren_rangliste, {}, "einzelschnueren_rangliste"),
    re_path(r'^rangliste/(?P<kategorie>[-\w]+)/pdf/$',
        views.einzelschnueren_rangliste_pdf, {}, "einzelschnueren_rangliste_pdf"),
    re_path(r'^kranzlimite/(?P<kategorie>[-\w]+)/update$',
        views.einzelschnueren_kranzlimite_update, {}, "einzelschnueren_kranzlimite_update"),
]

schwimmen_patterns = [
    re_path(r'^$',
        views.schwimmen_get, {}, "schwimmen_get"),
    re_path(r'^eingabe/$',
        views.schwimmen_eingabe, {}, "schwimmen_eingabe"),
    re_path(r'^update/(?P<startnummer>\d+)$',
        views.schwimmen_update, {}, "schwimmen_update"),
    re_path(r'^delete/(?P<startnummer>\d+)$',
        views.schwimmen_delete, {}, "schwimmen_delete"),
    re_path(r'^rangliste/$',
        views.schwimmen_rangliste, {}, "schwimmen_rangliste"),
    re_path(r'^rangliste/(?P<kategorie>[-\w]+)/$',
        views.schwimmen_rangliste, {}, "schwimmen_rangliste"),
    re_path(r'^rangliste/(?P<kategorie>[-\w]+)/pdf/$',
        views.schwimmen_rangliste_pdf, {}, "schwimmen_rangliste_pdf"),
    re_path(r'^kranzlimite/(?P<kategorie>[-\w]+)/update$',
        views.schwimmen_kranzlimite_update, {}, "schwimmen_kranzlimite_update"),
]

sektionsfahren_patterns = [
    re_path(r'^$',
        views.sektionsfahren_get, {}, "sektionsfahren_get"),
    re_path(r'^startliste/$',
        views.sektionsfahren_startliste, {}, "sektionsfahren_startliste"),
    re_path(r'^gruppe/add/$',
        views.sektionsfahren_gruppe_add, {}, "sektionsfahren_gruppe_add"),
    re_path(r'^gruppe/(?P<gruppe>[-\w]+)/$',
        views.sektionsfahren_gruppe_get, {}, "sektionsfahren_gruppe_get"),
    re_path(r'^gruppe/(?P<gruppe>[-\w]+)/update/$',
        views.sektionsfahren_gruppe_update, {}, "sektionsfahren_gruppe_update"),
    re_path(r'^gruppe/(?P<gruppe>[-\w]+)/delete/$',
        views.sektionsfahren_gruppe_delete, {}, "sektionsfahren_gruppe_delete"),
    re_path(r'^gruppe/(?P<gruppe>[-\w]+)/abzug/$',
        views.sektionsfahren_gruppe_abzug, {}, "sektionsfahren_gruppe_abzug"),
    re_path(r'^gruppe/(?P<gruppe>[-\w]+)/schiff/$',
        views.sektionsfahren_schiff_post, {}, "sektionsfahren_schiff_post"),
    re_path(r'^gruppe/(?P<gruppe>[-\w]+)/schiff/(?P<position>\d+)/update/$',
        views.sektionsfahren_schiff_update, {}, "sektionsfahren_schiff_update"),
    re_path(r'^postenblatt/$',
        views.sektionsfahren_postenblatt, {}, "sektionsfahren_postenblatt"),
    re_path(r'^postenblatt/(?P<posten>[-\w]+)/$',
        views.sektionsfahren_postenblatt, {}, "sektionsfahren_postenblatt"),
    re_path(r'^rangliste/$',
        views.sektionsfahren_rangliste, {}, "sektionsfahren_rangliste"),
    re_path(r'^rangliste/pdf/$',
        views.sektionsfahren_rangliste_pdf, {}, "sektionsfahren_rangliste_pdf"),
    re_path(r'^rangliste-gruppe/$',
        views.sektionsfahren_rangliste_gruppe, {}, "sektionsfahren_rangliste_gruppe"),
    re_path(r'^rangliste-schiffe/$',
        views.sektionsfahren_rangliste_schiff, {}, "sektionsfahren_rangliste_schiff"),
    re_path(r'^kranzlimiten/$',
        views.sektionsfahren_kranzlimiten, {}, "sektionsfahren_kranzlimiten"),
    re_path(r'^kranzlimiten/update/$',
        views.sektionsfahren_kranzlimiten_update, {}, "sektionsfahren_kranzlimiten_update"),
    re_path(r'^notenblatt/(?P<sektion_name>[-\w\s]+)/$',
        views.sektionsfahren_notenblatt, {}, "sektionsfahren_notenblatt"),
    re_path(r'^notenblatt/(?P<sektion_name>[-\w\s]+)/pdf$',
        views.sektionsfahren_notenblatt_pdf, {}, "sektionsfahren_notenblatt_pdf"),
    re_path(r'^notenblatt-gruppe/(?P<gruppe>[-\w]+)/$',
        views.sektionsfahren_notenblatt_gruppe, {}, "sektionsfahren_notenblatt_gruppe"),
    re_path(r'^notenblatt-gruppe/(?P<gruppe>[-\w]+)/pdf$',
        views.sektionsfahren_notenblatt_gruppe_pdf, {}, "sektionsfahren_notenblatt_gruppe_pdf"),
]

urlpatterns = [
    re_path(r'^$',
        views.wettkaempfe_get, name="wettkaempfe_get"),
    re_path(r'^add/$',
        views.wettkaempfe_add, {}, "wettkaempfe_add"),
    re_path(r'^(?P<jahr>\d+)/$',
        views.wettkaempfe_by_year, {}, "wettkaempfe_by_year"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/$',
        views.wettkampf_get, {}, "wettkampf_get"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/update/$',
        views.wettkampf_update, {}, "wettkampf_update"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/delete/$',
        views.wettkampf_delete_confirm, {}, "wettkampf_delete_confirm"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/rangliste/pdf/$',
        views.rangliste_komplett_pdf, {}, "rangliste_komplett_pdf"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/sektionsfahren/',
        include(sektionsfahren_patterns)),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/schwimmen/',
        include(schwimmen_patterns)),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/einzelschnueren/',
        include(einzelschnueren_patterns)),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/gruppenschnueren/',
        include(gruppenschnueren_patterns)),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/bootfaehrenbau/',
        include(bootfaehrenbau_patterns)),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/doppelstarter-einzelfahren/$',
        views.doppelstarter_einzelfahren, {}, "doppelstarter_einzelfahren"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/startlisten-einzelfahren-export/$',
        views.startlisten_einzelfahren_export, {}, "startlisten_einzelfahren_export"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/startlisten-einzelfahren-import/$',
        views.startlisten_einzelfahren_import, {}, "startlisten_einzelfahren_import"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/add/$',
        views.disziplinen_add, {}, "disziplinen_add"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/$',
        views.disziplin_get, {}, "disziplin_get"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/update/$',
        views.disziplin_update, {}, "disziplin_update"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/delete/$',
        views.disziplin_delete_confirm, {}, "disziplin_delete_confirm"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/posten/$',
        views.posten_list, {}, "posten_list"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/posten/(?P<posten>[-\w]+)$',
        views.posten_get, {}, "posten_get"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/posten/(?P<posten>[-\w]+)/update/$',
        views.posten_update, {}, "posten_update"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/posten/(?P<posten>[-\w]+)/delete/$',
        views.posten_delete_confirm, {}, "posten_delete_confirm"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/posten/(?P<posten>[-\w]+)/zeiten-einzelfahren-import/$',
        views.zeiten_einzelfahren_import, {}, "zeiten_einzelfahren_import"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/posten/(?P<posten>[-\w]+)/zeiten-sektionsfahren-import/$',
        views.zeiten_sektionsfahren_import, {}, "zeiten_sektionsfahren_import"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/posten/(?P<posten>[-\w]+)/noten-einzelfahren-import/$',
        views.noten_einzelfahren_import, {}, "noten_einzelfahren_import"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/startliste/$',
        views.startliste, {}, "startliste"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/startliste/pdf/$',
        views.startliste_einzelfahren_pdf, {}, "startliste_einzelfahren_pdf"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/teilnehmer/(?P<startnummer>\d+)/$',
        views.teilnehmer_get, {}, "teilnehmer_get"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/teilnehmer/(?P<startnummer>\d+)/update/$',
        views.teilnehmer_update, {}, "teilnehmer_update"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/teilnehmer/(?P<startnummer>\d+)/delete/$',
        views.teilnehmer_delete_confirm, {}, "teilnehmer_delete_confirm"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/bewertungen/$',
        views.bewertungen, {}, "bewertungen"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/postenblatt/(?P<posten>[-\w]+)/$',
        views.postenblatt, {}, "postenblatt"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/postenblatt/(?P<posten>[-\w]+)/update/$',
        views.postenblatt_update, {}, "postenblatt_update"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/richtzeiten/$',
        views.richtzeiten, {}, "richtzeiten"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/null-zeiten/$',
        views.einzelfahren_null_zeiten, {}, "einzelfahren_null_zeiten"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/sf-null-zeiten/$',
        views.sektionsfahren_null_zeiten, {}, "sektionsfahren_null_zeiten"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/richtzeiten/pdf/$',
        views.richtzeiten_pdf, {}, "richtzeiten_pdf"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/richtzeit/(?P<posten>[-\w]+)/$',
        views.richtzeit, {}, "richtzeit"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/richtzeit/(?P<posten>[-\w]+)/update/$',
        views.richtzeit_update, {}, "richtzeit_update"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/notenliste/$',
        views.notenliste, {}, "notenliste"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/notenliste/pdf/$',
        views.notenliste_pdf, {}, "notenliste_pdf"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/notenliste/pdf/alle-sektionen$',
        views.notenliste_pdf_all, {}, "notenliste_pdf_all"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/notenblaetter/$',
        views.notenblaetter_pdf, {}, "notenblaetter_pdf"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/rangliste/$',
        views.rangliste, {}, "rangliste"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/rangliste/pdf/$',
        views.rangliste_pdf_all, {}, "rangliste_pdf_all"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/rangliste/xlsx/$',
        views.rangliste_xlsx_all, {}, "rangliste_xlsx_all"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/rangliste/(?P<kategorie>[-\w]+)/$',
        views.rangliste, {}, "rangliste"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/rangliste/(?P<kategorie>[-\w]+)/pdf/$',
        views.rangliste_pdf, {}, "rangliste_pdf"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/beste-schiffe/$',
        views.beste_schiffe, {}, "beste_schiffe"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/(?P<kategorie>[-\w]+)/beste-saisonpaare/$',
        views.beste_saisonpaare, {}, "beste_saisonpaare"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/kranzlimiten/$',
        views.kranzlimiten, {}, "kranzlimiten"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/kranzlimiten/update$',
        views.kranzlimiten_update, {}, "kranzlimiten_update"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/notenblatt/$',
        views.notenblatt, {}, "notenblatt"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/notenblatt/(?P<startnummer>\d+)/$',
        views.notenblatt, {}, "notenblatt"),
    re_path(r'^(?P<jahr>\d+)/(?P<wettkampf>[-\w]+)/(?P<disziplin>[-\w]+)/notenblatt/(?P<startnummer>\d+)/pdf/$',
        views.notenblatt_pdf, {}, "notenblatt_pdf"),
]
