# Generated by Django 5.0.4 on 2024-04-25 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disziplin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disziplinart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sektion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wettkampf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique_for_year='von')),
                ('zusatz', models.CharField(max_length=100)),
                ('von', models.DateField(help_text='Format: JJJJ-MM-DD')),
                ('bis', models.DateField(blank=True, help_text='(optional)', null=True)),
                ('JPSM', models.BooleanField(default=False, help_text='Ist es eine JP SM? Hat Einfluss auf die Kategoriewahl bei der Startliste')),
            ],
            options={
                'ordering': ['-von'],
            },
        ),
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startnummer', models.PositiveIntegerField()),
                ('disqualifiziert', models.BooleanField(default=False)),
                ('ausgeschieden', models.BooleanField(default=False)),
                ('disziplin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.disziplin')),
            ],
            options={
                'ordering': ['startnummer'],
                'unique_together': {('disziplin', 'startnummer')},
            },
        ),
        migrations.AddField(
            model_name='disziplin',
            name='disziplinart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sasse.disziplinart'),
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('alter_von', models.PositiveSmallIntegerField()),
                ('alter_bis', models.PositiveSmallIntegerField()),
                ('reihenfolge', models.SmallIntegerField(default=1)),
                ('disziplinart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.disziplinart')),
            ],
            options={
                'ordering': ['reihenfolge'],
            },
        ),
        migrations.AddField(
            model_name='disziplin',
            name='kategorien',
            field=models.ManyToManyField(blank=True, null=True, to='sasse.kategorie'),
        ),
        migrations.CreateModel(
            name='Kranzlimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wert', models.DecimalField(decimal_places=1, max_digits=6)),
                ('disziplin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.disziplin')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Postenart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('disziplinarten', models.ManyToManyField(to='sasse.disziplinart')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Posten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('reihenfolge', models.PositiveIntegerField()),
                ('disziplin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.disziplin')),
                ('postenart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.postenart')),
            ],
            options={
                'ordering': ['reihenfolge', 'name'],
                'unique_together': {('disziplin', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Bewertungsart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppe', models.CharField(choices=[('ZIEL', 'Ziel'), ('STIL', 'Stil')], default='ZIEL', max_length=6)),
                ('name', models.CharField(max_length=50)),
                ('signum', models.SmallIntegerField(default=1)),
                ('einheit', models.CharField(choices=[('PUNKT', 'Punkte'), ('ZEIT', 'Zeit')], max_length=6)),
                ('defaultwert', models.DecimalField(decimal_places=1, max_digits=6)),
                ('wertebereich', models.CharField(max_length=200)),
                ('reihenfolge', models.SmallIntegerField(default=1)),
                ('editierbar', models.BooleanField(default=True)),
                ('postenart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.postenart')),
            ],
            options={
                'ordering': ['postenart', 'reihenfolge'],
            },
        ),
        migrations.CreateModel(
            name='Richtzeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('posten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.posten')),
            ],
        ),
        migrations.CreateModel(
            name='Mitglied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('vorname', models.CharField(max_length=50)),
                ('geburtsdatum', models.DateField()),
                ('geschlecht', models.CharField(choices=[('f', 'Frau'), ('m', 'Mann')], max_length=1)),
                ('sektion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.sektion')),
            ],
            options={
                'ordering': ['name', 'vorname', 'sektion'],
            },
        ),
        migrations.CreateModel(
            name='SektionsfahrenKranzlimiten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('silber', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('lorbeer', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('ausser_konkurrenz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sasse.sektion')),
                ('disziplin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.disziplin')),
            ],
        ),
        migrations.CreateModel(
            name='SpezialwettkaempfeKranzlimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(max_length=10)),
                ('zeit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disziplin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.disziplin')),
            ],
        ),
        migrations.AddField(
            model_name='disziplin',
            name='wettkampf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.wettkampf'),
        ),
        migrations.CreateModel(
            name='Bootfaehrengruppe',
            fields=[
                ('teilnehmer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sasse.teilnehmer')),
                ('name', models.CharField(max_length=20)),
                ('kategorie', models.CharField(default='Aktive', max_length=10)),
                ('zuschlaege', models.DecimalField(decimal_places=1, max_digits=6)),
                ('einbauzeit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ausbauzeit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('zeit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('sektion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.sektion')),
            ],
            bases=('sasse.teilnehmer',),
        ),
        migrations.CreateModel(
            name='Einzelschnuerer',
            fields=[
                ('teilnehmer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sasse.teilnehmer')),
                ('kategorie', models.CharField(max_length=10)),
                ('parcourszeit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('zuschlaege', models.DecimalField(decimal_places=2, max_digits=6)),
                ('zeit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('mitglied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.mitglied')),
            ],
            bases=('sasse.teilnehmer',),
        ),
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('teilnehmer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sasse.teilnehmer')),
                ('name', models.CharField(max_length=20)),
                ('abzug_gruppe', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6)),
                ('abzug_sektion', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6)),
                ('abzug_gruppe_comment', models.CharField(blank=True, max_length=400, null=True)),
                ('abzug_sektion_comment', models.CharField(blank=True, max_length=400, null=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.mitglied')),
                ('sektion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.sektion')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('sasse.teilnehmer',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('teilnehmer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sasse.teilnehmer')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.kategorie')),
                ('mitglied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.mitglied')),
                ('sektion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.sektion')),
            ],
            bases=('sasse.teilnehmer',),
        ),
        migrations.CreateModel(
            name='Schiffeinzel',
            fields=[
                ('teilnehmer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sasse.teilnehmer')),
                ('steuermann_ist_ds', models.BooleanField(default=False)),
                ('vorderfahrer_ist_ds', models.BooleanField(default=False)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.kategorie')),
                ('sektion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.sektion')),
                ('steuermann', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steuermann', to='sasse.mitglied')),
                ('vorderfahrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vorderfahrer', to='sasse.mitglied')),
            ],
            bases=('sasse.teilnehmer',),
        ),
        migrations.CreateModel(
            name='Schiffsektion',
            fields=[
                ('teilnehmer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sasse.teilnehmer')),
                ('position', models.PositiveSmallIntegerField()),
                ('ft1_steuermann', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ft1_steuermann', to='sasse.mitglied')),
                ('ft1_vorderfahrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ft1_vorderfahrer', to='sasse.mitglied')),
                ('ft2_steuermann', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ft2_steuermann', to='sasse.mitglied')),
                ('ft2_vorderfahrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ft2_vorderfahrer', to='sasse.mitglied')),
                ('gruppex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.gruppe')),
            ],
            options={
                'ordering': ['gruppex', 'position'],
                'unique_together': {('gruppex', 'position')},
            },
            bases=('sasse.teilnehmer',),
        ),
        migrations.CreateModel(
            name='Schnuergruppe',
            fields=[
                ('teilnehmer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sasse.teilnehmer')),
                ('name', models.CharField(max_length=20)),
                ('kategorie', models.CharField(choices=[('JP', 'JP'), ('Aktive', 'Aktive')], default='Aktive', max_length=10)),
                ('aufbauzeit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('abbauzeit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('zuschlaege', models.DecimalField(decimal_places=1, max_digits=6)),
                ('zeit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('sektion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.sektion')),
            ],
            bases=('sasse.teilnehmer',),
        ),
        migrations.CreateModel(
            name='Schwimmer',
            fields=[
                ('teilnehmer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sasse.teilnehmer')),
                ('kategorie', models.CharField(max_length=10)),
                ('zeit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('mitglied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.mitglied')),
            ],
            bases=('sasse.teilnehmer',),
        ),
        migrations.CreateModel(
            name='Bewertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('zeit', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bewertungsart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.bewertungsart')),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.teilnehmer')),
                ('posten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.posten')),
            ],
            options={
                'unique_together': {('teilnehmer', 'posten', 'bewertungsart')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='disziplin',
            unique_together={('wettkampf', 'name')},
        ),
        migrations.CreateModel(
            name='SektionsfahrenZeitimport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startnummer_calc', models.PositiveIntegerField()),
                ('posten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.posten')),
                ('schiffsektion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasse.schiffsektion')),
            ],
            options={
                'unique_together': {('posten', 'schiffsektion', 'startnummer_calc')},
            },
        ),
    ]
