# Generated by Django 5.0.4 on 2024-04-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasse', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gruppe',
            new_name='Sektionsfahrengruppe',
        ),
        migrations.AlterField(
            model_name='disziplin',
            name='kategorien',
            field=models.ManyToManyField(blank=True, to='sasse.kategorie'),
        ),
    ]
