# Generated by Django 5.0.4 on 2024-05-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasse', '0002_rename_gruppe_sektionsfahrengruppe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitglied',
            name='nummer',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='sektion',
            name='nummer',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
