# Generated by Django 5.0.4 on 2025-06-21 18:22

from django.db import migrations

def update_fahrchef(apps, schema_editor):
    Mitglied = apps.get_model("sasse", "Mitglied")
    Sektionsfahrengruppe = apps.get_model("sasse", "Sektionsfahrengruppe")

    for g in Sektionsfahrengruppe.objects.filter(disziplin__wettkampf_id=10): # Klingnau
        if g.startnummer == 49:
            g.chef = Mitglied.objects.get(nummer=1008407)
        elif g.startnummer == 39:
            g.chef = Mitglied.objects.get(nummer=1008410)
        elif g.startnummer == 35:
            g.chef = Mitglied.objects.get(nummer=1018888)
        elif g.startnummer == 18:
            g.chef = Mitglied.objects.get(nummer=1008474)
        elif g.startnummer == 7:
            g.chef = Mitglied.objects.get(nummer=1008474)
        elif g.startnummer == 22:
            g.chef = Mitglied.objects.get(nummer=1008474)
        elif g.startnummer == 55:
            g.chef = Mitglied.objects.get(nummer=1008319)
        elif g.startnummer == 54:
            g.chef = Mitglied.objects.get(nummer=1008540)
        elif g.startnummer == 23:
            g.chef = Mitglied.objects.get(nummer=1212368)
        elif g.startnummer == 42:
            g.chef = Mitglied.objects.get(nummer=1002334)
        elif g.startnummer == 26:
            g.chef = Mitglied.objects.get(nummer=1016638)
        elif g.startnummer == 41:
            g.chef = Mitglied.objects.get(nummer=1010010)
        elif g.startnummer == 32:
            g.chef = Mitglied.objects.get(nummer=25077)
        elif g.startnummer == 19:
            g.chef = Mitglied.objects.get(nummer=1010031)
        elif g.startnummer == 12:
            g.chef = Mitglied.objects.get(nummer=1010041)
        elif g.startnummer == 11:
            g.chef = Mitglied.objects.get(nummer=1007699)
        elif g.startnummer == 3:
            g.chef = Mitglied.objects.get(nummer=1010102)
        elif g.startnummer == 33:
            g.chef = Mitglied.objects.get(nummer=1008399)
        elif g.startnummer == 13:
            g.chef = Mitglied.objects.get(nummer=1002330)
        elif g.startnummer == 17:
            g.chef = Mitglied.objects.get(nummer=1010178)
        g.save()

    for g in Sektionsfahrengruppe.objects.filter(disziplin__wettkampf_id=35): # Mumpf
        if g.startnummer == 32:
            g.chef = Mitglied.objects.get(nummer=1008416)
        elif g.startnummer == 14:
            g.chef = Mitglied.objects.get(nummer=1007697)
        elif g.startnummer == 7:
            g.chef = Mitglied.objects.get(nummer=1008319)
        elif g.startnummer == 53:
            g.chef = Mitglied.objects.get(nummer=1008505)
        elif g.startnummer == 48:
            g.chef = Mitglied.objects.get(nummer=1012542)
        elif g.startnummer == 24:
            g.chef = Mitglied.objects.get(nummer=1008540)
        elif g.startnummer == 17:
            g.chef = Mitglied.objects.get(nummer=1212368)
        elif g.startnummer == 25:
            g.chef = Mitglied.objects.get(nummer=1002364)
        elif g.startnummer == 33:
            g.chef = Mitglied.objects.get(nummer=1002364)
        elif g.startnummer == 18:
            g.chef = Mitglied.objects.get(nummer=1002334)
        elif g.startnummer == 2:
            g.chef = Mitglied.objects.get(nummer=1009995)
        elif g.startnummer == 23:
            g.chef = Mitglied.objects.get(nummer=1002285)
        elif g.startnummer == 11:
            g.chef = Mitglied.objects.get(nummer=1010031)
        elif g.startnummer == 40:
            g.chef = Mitglied.objects.get(nummer=1010041)
        elif g.startnummer == 13:
            g.chef = Mitglied.objects.get(nummer=1007699)
        elif g.startnummer == 37:
            g.chef = Mitglied.objects.get(nummer=1007699)
        elif g.startnummer == 5:
            g.chef = Mitglied.objects.get(nummer=1010102)
        elif g.startnummer == 22:
            g.chef = Mitglied.objects.get(nummer=1010078)
        elif g.startnummer == 3:
            g.chef = Mitglied.objects.get(nummer=1010151)
        elif g.startnummer == 41:
            g.chef = Mitglied.objects.get(nummer=1010185)
        g.save()

    for g in Sektionsfahrengruppe.objects.filter(disziplin__wettkampf_id=79): # Bremgarten
        if g.startnummer == 18:
            g.chef = Mitglied.objects.get(nummer=1008367)
        elif g.startnummer == 19:
            g.chef = Mitglied.objects.get(nummer=1008416)
        elif g.startnummer == 48:
            g.chef = Mitglied.objects.get(nummer=1007697)
        elif g.startnummer == 51:
            g.chef = Mitglied.objects.get(nummer=1008468)
        elif g.startnummer == 1:
            g.chef = Mitglied.objects.get(nummer=1008484)
        elif g.startnummer == 2:
            g.chef = Mitglied.objects.get(nummer=1008484)
        elif g.startnummer == 7:
            g.chef = Mitglied.objects.get(nummer=1008319)
        elif g.startnummer == 45:
            g.chef = Mitglied.objects.get(nummer=1012542)
        elif g.startnummer == 53:
            g.chef = Mitglied.objects.get(nummer=1013420)
        elif g.startnummer == 36:
            g.chef = Mitglied.objects.get(nummer=1002364)
        elif g.startnummer == 44:
            g.chef = Mitglied.objects.get(nummer=1002364)
        elif g.startnummer == 50:
            g.chef = Mitglied.objects.get(nummer=1002334)
        elif g.startnummer == 39:
            g.chef = Mitglied.objects.get(nummer=1002341)
        elif g.startnummer == 35:
            g.chef = Mitglied.objects.get(nummer=1009995)
        elif g.startnummer == 47:
            g.chef = Mitglied.objects.get(nummer=1010031)
        elif g.startnummer == 40:
            g.chef = Mitglied.objects.get(nummer=1010041)
        elif g.startnummer == 3:
            g.chef = Mitglied.objects.get(nummer=1014827)
        elif g.startnummer == 49:
            g.chef = Mitglied.objects.get(nummer=1008193)
        elif g.startnummer == 24:
            g.chef = Mitglied.objects.get(nummer=1010103)
        elif g.startnummer == 14:
            g.chef = Mitglied.objects.get(nummer=1010078)
        elif g.startnummer == 32:
            g.chef = Mitglied.objects.get(nummer=1010159)
        elif g.startnummer == 43:
            g.chef = Mitglied.objects.get(nummer=1010185)
        elif g.startnummer == 10:
            g.chef = Mitglied.objects.get(nummer=1010260)
        elif g.startnummer == 27:
            g.chef = Mitglied.objects.get(nummer=1406088)
        g.save()

    for g in Sektionsfahrengruppe.objects.filter(disziplin__wettkampf_id=99): # Aarburg
        if g.startnummer == 1:
            g.chef = Mitglied.objects.get(nummer=1008416)
        elif g.startnummer == 2:
            g.chef = Mitglied.objects.get(nummer=1008416)
        elif g.startnummer == 39:
            g.chef = Mitglied.objects.get(nummer=1007697)
        elif g.startnummer == 6:
            g.chef = Mitglied.objects.get(nummer=1008484)
        elif g.startnummer == 13:
            g.chef = Mitglied.objects.get(nummer=1008484)
        elif g.startnummer == 34:
            g.chef = Mitglied.objects.get(nummer=1008319)
        elif g.startnummer == 23:
            g.chef = Mitglied.objects.get(nummer=1008523)
        elif g.startnummer == 44:
            g.chef = Mitglied.objects.get(nummer=1017454)
        elif g.startnummer == 16:
            g.chef = Mitglied.objects.get(nummer=1017100)
        elif g.startnummer == 9:
            g.chef = Mitglied.objects.get(nummer=1016998)
        elif g.startnummer == 32:
            g.chef = Mitglied.objects.get(nummer=1019216)
        elif g.startnummer == 33:
            g.chef = Mitglied.objects.get(nummer=1002341)
        elif g.startnummer == 17:
            g.chef = Mitglied.objects.get(nummer=1008605)
        elif g.startnummer == 29:
            g.chef = Mitglied.objects.get(nummer=1009996)
        elif g.startnummer == 24:
            g.chef = Mitglied.objects.get(nummer=1010039)
        elif g.startnummer == 28:
            g.chef = Mitglied.objects.get(nummer=1019360)
        elif g.startnummer == 11:
            g.chef = Mitglied.objects.get(nummer=1018163)
        elif g.startnummer == 43:
            g.chef = Mitglied.objects.get(nummer=1018010)
        elif g.startnummer == 3:
            g.chef = Mitglied.objects.get(nummer=1010103)
        elif g.startnummer == 30:
            g.chef = Mitglied.objects.get(nummer=1010123)
        elif g.startnummer == 38:
            g.chef = Mitglied.objects.get(nummer=1010123)
        elif g.startnummer == 35:
            g.chef = Mitglied.objects.get(nummer=1014710)
        elif g.startnummer == 41:
            g.chef = Mitglied.objects.get(nummer=1014710)
        g.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sasse', '0008_eidg_und_generationen'),
    ]

    operations = [
        migrations.RunPython(update_fahrchef),
    ]
